In [ ]:
import os
import pandas
import board
import busio
import adafruit_bmp3xx
import adafruit_lsm303_accel
import adafruit_lsm303dlh_mag
import time
import picamera

# Delete the csvs if they already exist to eliminate any confusion
for file_name in os.listdir('/home/pi/RISE/data'):
    if file_name.endswith('.csv'):
        os.remove(f'/home/pi/RISE/data/{file_name}')

# Set up I2C and sensors
i2c = busio.I2C(board.SCL, board.SDA)
bmp = adafruit_bmp3xx.BMP3XX_I2C(i2c)
accel = adafruit_lsm303_accel.LSM303_Accel(i2c)
mag = adafruit_lsm303dlh_mag.LSM303DLH_Mag(i2c)

# DataFrame with columns time, temp, pressure, 3 for acceleraton and 3 for magnetometer
df = pandas.DataFrame(columns=['time','temperature','pressure',
                               'acc_x','acc_y','acc_z',
                               'mag_x','mag_y','mag_z'])

# Set up camera stuff.
### MAYBE ALSO ITERATE THE CAMERA RECORDINGS ###
# cam = picamera.PiCamera() #intialize camera
# cam.resolution = (640, 480)
# camera.framerate = 90
# cam.start_recording('video.h264') #start recording and name video file

# Define start time, delay, and the record time
start_time = time.time()
delay_time = 5
record_time = 20

# iterating parameters
i = 0
iters = 20

# FOR TESTING
print('Start')

while time.time() - start_time < delay_time + record_time:
    # Update elapsed time with every run
    elapsed_time = time.time() - start_time
    # Skip everything else if we're still in the delay period
    if elapsed_time < delay_time:
        continue
    # Otherwise, append data to dataframe
    df = df.append({'time':(elapsed_time - delay_time),
                    'temperature':bmp.temperature,
                    'pressure':bmp.pressure,
                    'acc_x':accel.acceleration[0],
                    'acc_y':accel.acceleration[1],
                    'acc_z':accel.acceleration[2],
                    'mag_x':mag.magnetic[0],
                    'mag_y':mag.magnetic[1],
                    'mag_z':mag.magnetic[2]},
                    ignore_index=True)
    # start the counter
    i += 1
    # save a file every so often to ensure bullet-proofness depending on iterations
    if (i % iters) == 0:
        fo = open(f'/home/pi/RISE/data/data_temporary_{int(i / iters)}.csv')
        df.to_csv(f'/home/pi/RISE/data/data_temporary_{int(i / iters)}.csv', index = False)
        # FOR TESTING
        fo.close()

        print('data saved!')

# save all the data in one file, if the program ran successfully
df.to_csv('/home/pi/RISE/data/data.csv', index = False)

# Delete the temporary files if the program ran successfully
for file_name in os.listdir('/home/pi/RISE/data'):
    if file_name.startswith('data_temporary') and file_name.endswith('.csv'):
        os.remove(f'/home/pi/RISE/data/{file_name}')

# Stop the camera recording
#cam.stop_recording()

# FOR TESTING
print('Finished')
print(elapsed_time)


In [18]:
import numpy as np

for i in 100

x = np.array([])

y = np.append(x, [1, 2, 3])

print(y)

[1. 2. 3.]


In [35]:
import numpy

a = numpy.array([[1, 2, 3]])

newArray = numpy.append(a, [[50, 60, 70]], axis = 0)

n = numpy.array([[i, (elapsed_time - delay_time), bmp.temperature, bmp.pressure, 
                 accel.acceleration[0], accel.acceleration[1], accel.acceleration[2], 
                 mag.magnetic[0], mag.magnetic[1], mag.magnetic[2]]])

print(newArray)

[[ 1  2  3]
 [50 60 70]]


In [44]:
a = numpy.array([[1, 2, 3]])

newArray = np.append(a, [[50, 60, 70]], axis = 0)

print(newArray)

[[ 1  2  3]
 [50 60 70]]


In [74]:
newArray = np.append(a, [[50, 60, 70]], axis = 0)

print(newArray) 

[[ 1  2  3]
 [50 60 70]]


In [ ]:
import numpy as np

step_n = 10
steps = np.random.choice([[-1, 0, 1], size=(1,2))
for n in range(step_n-1):
    step = np.random.choice([-1, 0, 1], size=(1,2))
    print(steps)
    steps = np.append(steps, step, axis=0)
    #something will be checked after each n

print(steps)